### ISSUE TITLE
DCV: Add support to refresh dereferencing

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/visualizations#48]
![image](https://cloud.githubusercontent.com/assets/718827/13662376/3e3123a0-e69a-11e5-81c3-6310bd4e0c0e.png)

This happens especially when starting the RUIAN virtuoso freshly and dereferencing goes slow. Some of the labels are then left undereferenced.

**Comment by jirihelmich** [comment]
The dereferencing is now a system-wide thing used everywhere automatically
if label is not present. It's an angular label filter. ( | label )

I think that the problem is rather in configuration of the dereferening
service, the timeout is still too pedant. Will increase that.
Thu, 10 Mar 2016 v 08:32 odesílatel Jakub Klímek notifications@github.com
napsal:
